### ISSUE TITLE
Packages for CentOS 9 / EL9 missing on packagecloud

### ISSUE THREAD

**Issue by der-eismann** [rabbitmq/erlang-rpm#101]
Hello! I noticed that you are publishing artifacts for el9 with your [recent releases](https://github.com/rabbitmq/erlang-rpm/releases/tag/v24.3.4). However they are missing in the [packagecloud repo](https://packagecloud.io/rabbitmq/erlang), there I can only find the el8 builds. Could you maybe push them there as well?

**Comment by michaelklishin** [comment]
They are intentionally not published there because CentOS Stream 9 is not yet GA or at least it was not at the time we introduced .el9 packages.

PackageCloud the service does not support CentOS Stream 9 as a distribution so you cannot specify it when publishing packages.

.el8 packages work perfectly fine on CentOS Stream 9, cutting edge Fedora, Rocky Linux, and so on.
