### ISSUE TITLE
LDAP authentication is not working after erlang upgrade

### ISSUE THREAD

**Issue by alekxx** [rabbitmq/erlang-rpm#49]
I'm using rabbit_auth_backend_ldap plugin to authenticate in LDAP. After upgrading erlang to erlang-18.3.4-5 or 19.2.3-1 I cannot login to management console using domain user and get following error 
```
=ERROR REPORT==== 1-Mar-2017::11:17:33 ===
webmachine error: path="/api/whoami"
"Unauthorized"

=INFO REPORT==== 2-Mar-2017::10:43:08 ===
LDAP CHECK: login for _username_

=INFO REPORT==== 2-Mar-2017::10:43:08 ===
    LDAP connect error: {error,"connect failed"}

=INFO REPORT==== 2-Mar-2017::10:43:08 ===
    LDAP connect error: {error,"connect failed"}

=INFO REPORT==== 2-Mar-2017::10:43:08 ===
LDAP DECISION: login for _username_: {error,"connect failed"}

=WARNING REPORT==== 2-Mar-2017::10:43:08 ===
HTTP access denied: rabbit_auth_backend_ldap failed authenticating _username_: "connect failed"
```
It's working correctly for erlang-18.3-1 so I had to downgrade erlang. 
My Rabbit is connecting to LDAP servers over SSL.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Our team does not maintain Erlang/OTP. We only package it in a more convenient to install way.

**Comment by michaelklishin** [comment]
I recall a couple of rabbitmq-users threads like this but only [one of them](https://groups.google.com/forum/#!searchin/rabbitmq-users/LDAP$20TLS%7Csort:relevance/rabbitmq-users/igbac-SR1FU/7HJdIwN-CQAJ) is recent (and the poster hasn't reported back).
