### ISSUE TITLE
asn1.app not found on CentOS 7.4

### ISSUE THREAD

**Issue by DatPhanTien** [rabbitmq/erlang-rpm#62]
Dear

I installed rabbitmq-server 3.7.5 on CentOS 7.4
I used the erlang zero dependencies 20.1.7-1.el7.centos for this rbmq.

However, when I start the service, I got this error:

'{"init terminating in do_boot",{error,{"no such file or directory","asn1.app"}}}'

Do you know how to fix this error?

Best
Dat

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This has been [discussed on rabbitmq-users before](https://groups.google.com/d/msg/rabbitmq-users/f3yYAFl-3lI/cHi_sMyuCAAJ) and usually a result of other Erlang packages not being uninstalled prior to installing this RPM.
