### ISSUE TITLE
Installation failed due to error "Public key for erlang-21.1.1-1.el7.centos.x86_64.rpm is not installed"

### ISSUE THREAD

**Issue by hellosmith420** [rabbitmq/erlang-rpm#64]
I am trying to install erlang-21.1.1-1.el7.centos.x86_64.rpm in a RHEL7 VM
But getting following error.
warning: /home/gr43011/erlang-21.1.1-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 6026dfca: NOKEY

Public key for erlang-21.1.1-1.el7.centos.x86_64.rpm is not installed

Where to get the keyfile for github releases.

Thanks,
John

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
It's a warning, not an error.

It depends on whether package was installed from. See [RabbitMQ Signing Keys](https://www.rabbitmq.com/signatures.html).

**Comment by antoinetran** [comment]
I reproduced this error (this is an error if we enforce gpgcheck, which should be enabled by default in production). To not disturb this github tracker but redirect other users with the same error, I sent a message in mailing user, as requested:
https://groups.google.com/forum/#!topic/rabbitmq-users/8sAuLV_oGh4
