### ISSUE TITLE
AArch64 packages

### ISSUE THREAD

**Issue by hrw** [rabbitmq/erlang-rpm#88]
While RabbitMQ is architecture agnostic Erlang is not. So newer version of RabbitMQ are not usable on !x86 architectures.

Please provide AArch64 packages so we can deploy OpenStack on our servers with something fresher than 3.7.10 (last ver working with CentOS 7 Erlang).

**Comment by michaelklishin** [comment]
I'm afraid our team never intended to be the king of Erlang packaging, so we very likely won't be covering ARM architectures unless there is a trivial way to cross-compile.

You have a few options:

 * Use [kerl](https://github.com/kerl/kerl/) to build from source
 * Use this open source package and adapt it for ARM64
 * Reach out to Erlang Solutions about ARM64 packages
 * Ask on the Erlang mailing list for more options

Note that the Erlang/OTP team at Ericsson would not be interested in packaging improvements. In our experience, they believe that packaging is something for the community to worry about, which is why we have given up and decided to build Erlang packages for two most popular distribution families and one most popular architecture.

**Comment by hrw** [comment]
Thanks. Will take a look at how your scripts work and in worst case create own repo.

**Comment by michaelklishin** [comment]
I chatted with @gerhard and he suggested a couple more things. You can look into deploying RabbitMQ in containers. We already have a [fairly mature image](https://github.com/docker-library/rabbitmq) which the community maintains, and it is updated within 24 hours when a new RabbitMQ, Erlang or OpenSSL versions come out.

For us to produce an ARM64 package would require adding an ARM64 Concourse worker which would not be used for anything else. Currently, there isn't enough demand to justify it, even though we would like to make the latest Erlang version availability a solved problem, we have to focus.
