### ISSUE TITLE
Error: Package: rabbitmq-server-3.7.9-1.el7.noarch (/rabbitmq-server-3.7.9-1.el7.noarch)            Requires: erlang >= 19.3

### ISSUE THREAD

**Issue by koperait** [rabbitmq/erlang-rpm#89]
Hi!
# yum localinstall rabbitmq-server-3.7.9-1.el7.noarch.rpm
...
Error: Package: rabbitmq-server-3.7.9-1.el7.noarch (/rabbitmq-server-3.7.9-1.el7.noarch)
           Requires: erlan
  Available: erlang-R16B-03.18.el7.x86_64 (X5_Retail_Group_EPEL_7_x86_64_epel_7_x86_64)
               erlang = R16B-03.18.el7
...

but im have not installed erlang on my server now

[root@oleg]# yum list installed | grep erlang
[root@oleg]# erl
bash: /bin/erl: No such file or directory
[root@oleg]# cat /usr/lib/erlang/releases/RELEASES
cat: /usr/lib/erlang/releases/RELEASES: No such file or directory
[root@oleg]#

im install esl-erlang_21.1-1~centos~7_amd64.rpm, but error  saved =(

0_o what is it??

And how i can fix it?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`esl-erlang` is a package maintained by Erlang solutions and is different from this package. We do not maintain it.

You are welcome to post your question to the RabbitMQ mailing list but will be asked to provide an exact set of steps to reproduce what you are seeing. [This package's README](https://github.com/rabbitmq/erlang-rpm) explains how to set up a PackageCloud or Bintray repository to install it from. You can install the downloaded RPM directly as well.
